### PR TITLE
[Feature] attraction api and categories api

### PR DESCRIPTION
**Pull request by ting-yang14**
盧廷洋
http://43.206.54.81:3000/api/attractions?page=1
http://43.206.54.81:3000/api/attractions?page=0&keyword=藝文館所 
http://43.206.54.81:3000/api/attractions?page=0&keyword=北 
http://43.206.54.81:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK, But ...

1. It's much better to use `LIMIT` in SQL to do pagination.
2. It's much better to get ALL paginated attraction data at once by `JOIN` and listed column names, rather than get IDs for getting attraction data one by one.

Fix issues above and re-request review.

**Comment by ting-yang14** [comment]
Fix issues above
use `JOIN` to get all attraction data at once and  use `GROUP_CONCAT`  to concatenate multi-row image url
paginate attraction data by page number

**Review by cwpeng — CHANGES_REQUESTED** [review]
Try to use `LIMIT` in SQL to do pagination, not in your own code.

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Pull request merged**
